---
apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: productcatalog-handler
  namespace: product
spec:
  status:
    code: 16
    message: You are not authorized to access the service
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: productcatalog-denyrequest
  namespace: product
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: carspi-deny
  namespace: product
spec:
  match: destination.labels["app"] == "product-catalog" && destination.namespace == "product" && request.headers["authorization"] == "unauthorized"
  actions:
  - handler: productcatalog-handler.denier.myproject
    instances: [productcatalog-denyrequest.checknothing.myproject]