--- 
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpec
metadata: 
  name: product-catalog-auth-policy
  namespace: product
spec: 
  jwts: 
    - issuer: https://secure-sso-rh-sso.microservice.red/auth/realms/master
      jwks_uri: https://secure-sso.rh-sso:8443/auth/realms/master/protocol/openid-connect/certs
      audiences: 
      - inventoryservice
      forward_jwt: true     
--- 
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpecBinding
metadata:
  name: product-catalog-auth-policy-binding
  namespace: product
spec:
  policies:
    - name: product-catalog-auth-policy
      namespace: product
  services:
    - name: product-catalog
      namespace: product