apiVersion: v1
kind: Template
metadata:
  name: inventory-sso-config
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: keycloak-properties
  data:
    realm: "master"
    realm-key: ${RH_SSO_REALM_KEY}
    resource: "inventoryservice"
    auth-server-url: https://${RH_SSO_URL}/auth
    credentails-secret: ${RH_SSO_CREDENTIAL_SECRET}
parameters:
- description: rh-ss realm key
  required: true
  name: RH_SSO_REALM_KEY
- description: rh-sso service url
  required: true
  name: RH_SSO_URL     
- description: rh-sso credential secret
  required: true
  name: RH_SSO_CREDENTIAL_SECRET 