kind: ConfigMap
apiVersion: v1
metadata:
  name: keycloak-properties
data:
  realm: "demorealm"
  realm-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsxw1l9pzwXn0uelv3zgkwbZx1yNhDUxj/G7wUKb9B7WKLLqrat3XwUkoWmBh3BdJqX8/QGPu6jsQisM076b1ShlRK5z3nUqeP1A5J7x+pPep3n4ztjc05ilmiDkgqC1k/31jIXLsoGyNowFDJqy0pkleKpUURQCvy2/PtGg5dREuzXdJmKaj3EcnkVTbw89Wp5yUbgOMCAg8V2Dcl9naqVb6VlM8fpkDEwXjC1zqc3ouwr7HPVtU1hUUUHFq2IhHDnn9CZZIGwQ26WUPfusH3K2tue+hVoP6Fs5m4JGSg/NkHN4XMW9KijmSCJ8CSM4/IzZbMmw2lIOsFaYVCzRWawIDAQAB"
  resource: "inventoryservice"
  auth-server-url: "https://secure-sso-myproject.192.168.42.67.nip.io/auth"
  credentails-secret: "3b17e47e-9fc5-406b-9cb2-a7a6b8a87c41"