---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: product-catalog
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: product-catalog@sha256:cbb984764df6e48f1d12c554968ba23d9e72e63ece0d29f9503de7e336e2efd2
        namespace: myproject
      name: latest
