---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: crunchy-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 400M
---      
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csv-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100M      