apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpec
metadata: 
  name: product-catalog-auth-policy  
  namespace: product
spec: 
  jwts: 
    - issuer: http://sso-sso.192.168.64.2.nip.io/auth/realms/product
      jwks_uri: http://sso-sso.192.168.64.2.nip.io/auth/realms/product/protocol/openid-connect/certs 
      audiences: 
      - product-client
--- 
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpecBinding
metadata:
  name: product-catalog-auth-policy-binding
  namespace: product
spec:                                       
  policies: 
    - name: product-catalog-auth-policy      
      namespace: product
  services:                                                                                                                         
    - name: product-catalog
      namespace: product