apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: handler
  namespace: myproject
spec:
  status:
    code: 18
    message: Not Authorized
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denyrequest
  namespace: myproject
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denycarsapi
  namespace: myproject
spec:
  match: destination.service == "cars-api.myproject.svc.cluster.local" && request.headers["authorization"] == "unauthorized"
  actions:
  - handler: handler.denier
    instances: [ denyrequest.checknothing]