apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpec
metadata: 
  name: product-catalog-auth-policy  
  namespace: product
spec: 
  jwts: 
    - issuer: https://secure-sso-rh-sso.microservice.red/auth/realms/master
      jwks_uri: https://secure-sso-rh-sso.microservice.red/auth/realms/master/protocol/openid-connect/certs 
      audiences: 
      - curl
      forward_jwt: true
      #public_key_cache_duration: 0
 # https://github.com/istio/istio/blob/49485f1c0787028e95e6de73cf597c333724b773/pilot/test/mock/config.go#L136
--- 
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpecBinding
metadata:
  name: product-catalog-auth-policy-binding
  namespace: product
spec:                                       
  policies: 
    - name: product-catalog-auth-policy      
      namespace: product
  services:                                                                                                                         
    - name: product-catalog
      namespace: product
 # See - https://groups.google.com/forum/#!topic/istio-security/DzLR6Gqqjxk