apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpec
metadata: 
  name: cars-api-auth-policy  
  namespace: myproject
spec: 
  jwts: 
    - issuer: http://sso-myproject.192.168.64.2.nip.io/auth/realms/istio
      jwks_uri: http://sso-myproject.192.168.64.2.nip.io/auth/realms/istio/protocol/openid-connect/certs 
      audiences: 
      - curl
      #forward_jwt: true
 # https://github.com/istio/istio/blob/49485f1c0787028e95e6de73cf597c333724b773/pilot/test/mock/config.go#L136
--- 
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpecBinding
metadata:
  name: cars-api-auth-policy-binding
  namespace: myproject
spec:                                       
  policies: 
    - name: cars-api-auth-policy      
      namespace: myproject
  services:                                                                                                                         
    - name: cars-api
      namespace: myproject
 # See - https://groups.google.com/forum/#!topic/istio-security/DzLR6Gqqjxk